name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          cache: npm
      - uses: pnpm/action-setup@v2
        with:
          version: 7.3.0

      - name: Install Dependencies
        run: pnpm install

      # - name: Build Packages
      #   run: pnpm run docs:build

      - name: Build Docs
        run: pnpm run docs:release:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: my-vue-press/dlqbq.github.io
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAGE_TOKEN }}
